import { StyleSheet } from 'react-native';

const styles = (isDarkMode: boolean) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: isDarkMode ? '#121212' : '#ffffff',
    },
    map: {
        flex: 1,
    },
    inputContainer: {
        position: 'absolute',
        top: 12,
        left: 12,
        right: 12,
        backgroundColor: isDarkMode ? '#222222' : 'white',
        borderRadius: 5,
        paddingHorizontal: 45,
        paddingVertical: 15,
        zIndex: 1,
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        borderWidth: 1,
        borderColor: isDarkMode ? '#555555' : '#ddd',
        borderRadius: 5,
    },
    input: {
        flex: 1,
        padding: 10,
        backgroundColor: isDarkMode ? '#333333' : '#f1f1f1',
        borderRadius: 5,
        color: isDarkMode ? '#ffffff' : '#000000',
        fontSize: 14,
        height: 40,
    },
    inputWithButton: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: isDarkMode ? '#555555' : '#ddd',
        marginBottom: 10,
    },
    currentLocationButton: {
        padding: 10,
        backgroundColor: isDarkMode ? '#333333' : '#f1f1f1',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopRightRadius: 5,
        borderBottomRightRadius: 5,
        margin: 10,
    },
    currentLocationButtonText: {
        fontWeight: 'bold',
        color: 'white'
    },
    currentLocationIcon: {
        width: 20,
        height: 20,
    },
    backButton: {
        position: 'absolute',
        top: 10,
        left: 10,
        padding: 15,
        zIndex: 2,
    },
    backButtonText: {
        color: 'white',
        fontWeight: 'bold',
    },
    suggestion: {
        padding: 10,
        backgroundColor: isDarkMode ? '#333333' : 'white',
        borderRadius: 5,
        marginVertical: 4,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        color: isDarkMode ? '#ffffff' : '#000000',
    },
    suggestionsContainer: {
        backgroundColor: isDarkMode ? '#333333' : 'white',
        borderRadius: 5,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        maxHeight: 200,
    },
    buttonContainer: {
        marginTop: 10,
    },
    routeInfo: {
        position: 'absolute',
        bottom: 10,
        left: 10,
        right: 10,
        backgroundColor: isDarkMode ? '#222222' : 'white',
        borderRadius: 5,
        padding: 10,
        zIndex: 1,
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    routeText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: isDarkMode ? '#ffffff' : '#000000',
    },
    tagContainer: {
        position: 'absolute',
        backgroundColor: isDarkMode ? '#333333' : 'white',
        padding: 5,
        borderRadius: 5,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        color: isDarkMode ? '#ffffff' : '#000000',
    },
    tagText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: isDarkMode ? '#ffffff' : '#000000',
    },
    instructionContainer: {
        marginTop: 10,
        backgroundColor: 'green',
        alignItems: 'center',
        position: 'absolute',
        top: 10,
        left: 10,
        right: 10,
        zIndex: 2,
        borderRadius: 5,
        padding: 10,
    },
    instructionText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
    },
    profileButton: {
        position: 'absolute',
        top: 20,
        right: 10,
        zIndex: 2,
        padding: 10,
        backgroundColor: isDarkMode ? 'white' : '#222222',
        borderRadius: 25,
    },
    profileImage: {
        width: 15,
        height: 15,
        borderRadius: 10,
        paddingEnd: 15
    },
    chatContainer: {
        position: 'absolute',
        bottom: 10,
        left: 10,
        right: 10,
        backgroundColor: isDarkMode ? '#222' : '#fff',
        borderRadius: 5,
        padding: 10,
        zIndex: 2,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    closeButton: {
        alignSelf: 'flex-end',
        padding: 5,
    },
    closeButtonText: {
        color: isDarkMode ? '#fff' : '#000',
        fontWeight: 'bold',
    }
});

export default styles;
